[tool.poetry]
name = "simple-mockforce"
version = "0.1.0"
description = ""
authors = ["Alex Drozd <drozdster@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-soql-parser = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
simple-salesforce = "^1.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
